### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by annahosanna** [atom-ide-community/ide-python#222] opened 2020-11-11 17:29 UTC
When Atom starts:

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.6.1

### Stack Trace

Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

```
At C:\Users\meier011\.atom\packages\ide-python\node_modules\rxjs-compat\bundles\rxjs-compat.umd.min.js:16

TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Fa (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:113:292)
    at /packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:27:339)
    at a._innerSub (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:416)
    at a._tryNext (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:320)
    at a._next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:148)
    at a.next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:65:253)
    at a.notifyNext (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:120:125)
    at a._next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:116:50)
    at a.next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:65:253)
    at /packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:94:79
    at /packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:27:344)
    at a._innerSub (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:416)
    at a._tryNext (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:320)
    at a._next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:148)
    at a.next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:65:253)
    at b._subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:94:79)
    at b._trySubscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:376)
    at b.subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:161)
    at b.call (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:118:338)
    at b.subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:34)
    at b.call (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:118:338)
    at b.subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:34)
    at b.call (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:118:338)
    at b.subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:34)
    at listenToRemoteDebugCommands (/packages/ide-python/dist/debugger/utils.js:85:6)
    at activate (/packages/ide-python/dist/debugger/main.js:34:92)
    at PythonLanguageClient.activate (/packages/ide-python/dist/main.js:47:24)
    at Package.activateNow (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3699687)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1190051)
```

### Commands

```
```

### Non-Core Packages

```
auto-detect-indentation 1.3.0 
auto-indent 0.5.0 
base64 0.8.0 
busy-signal 2.0.1 
compare-files 0.8.1 
docblockr 0.13.7 
file-types 1.0.1 
highlight-bad-chars 2.0.0 
highlight-selected 0.17.0 
ide-python 1.6.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
json-converter 0.2.4 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-jenkinsfile 0.1.1 
language-powershell 5.0.0 
linter 3.1.1 
linter-js-yaml 1.4.6 
linter-ui-default 2.1.4 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.2 
minimap-split-diff 0.3.7 
multiline-tab 0.2.1 
pretty-json 2.1.2 
semanticolor 3.7.0 
sort-lines 0.19.0 
split-diff 1.6.1 
tabs-to-spaces 1.0.5 
```

**Comment by aminya** [comment] 2020-11-11 17:43
Duplicate of https://github.com/atom-ide-community/ide-python/issues/223

**Closed by aminya** 2020-11-11 17:43 UTC
